### ISSUE TITLE
Better Proxy Support

### ISSUE THREAD

**Issue by TheAlan404** [ParadigmMC/mcman#10]
a better support for proxy networks (velocity, waterfall, bungeecord)

folder structure would look something like this:

- network.toml
  - proxy/
    - server.toml
  - lobby/
    - server.toml
  - survival/
    - server.toml
  - creative/
    - server.toml
 
`network.toml`

```toml
name = "Cool Ass Server:tm"
proxy = "proxy" # folder/server name
port = "25565"

[servers.lobby]
port = 25566
# ...
[servers.creative]
port = 25567
# ...etc

[variables]
some_var = "1"
# exported as "nw_some_var" or "network_some_var"

[[groups.games.plugins]]
# downloadable
```

## groups

servers would be able to be grouped and every group would have its own "preset" plugins/mods and config files.

## special variables

```
NW_VELOCITY_SERVERS

[servers]
lobby = "25566"
creative = "25567"
```

```
NW_PROXY_SERVERS

servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25565
    restricted: false
```
smth like that idk
