### ISSUE TITLE
RFC: .mcman.dl - Some file for Downloadable

### ISSUE THREAD

**Issue by TheAlan404** [ParadigmMC/mcman#13]
Lets say theres a plugin named `Banana`

And lets also say Banana has a directory in `*/plugins/banana/assets` which contain some "assets"

A special file of some sorts could be used in `config/plugins/banana/assets/a.mcman.dl` which would contain a Downloadable:

```toml
type = "url"
url = "..."
```

This would basically allow using downloadables in every directory and not only `plugins`/`mods`/datapacks

Maybe the file extension could be changed:
- `.dl`
- `.dl.toml`
- `.mcman`
- `.mcman.toml`

These are the few i got on my mind, idk

**Comment by TheAlan404** [comment]
Maybe an `mcman.index.toml`/`mcman.folder.toml` is better?

```toml
[[files]]
type = "url"
url = "..."

[[files]]
type = "..."
```

This can also be expanded to include more features later on, maybe:

```toml
# dont want to nest like hell in config/?
destination = "plugins/Banana/addons/translations/data/lang"
```
