### ISSUE TITLE
(feat) Worlds

### ISSUE THREAD

**Issue by TheAlan404** [ParadigmMC/mcman#26]
I'm thinking of this:

- a `worlds/` folder with `.zip` files (or maybe `.tar.gz`)
- `mcman world pack <name>`
- `mcman world unpack <name>`

and also

```toml
# unsure about this one tbh
[worlds.plotworld.download]
type = "url"
url = "..."
```

On build, the `worlds/` would be unpacked (unzipped) to `server/` (output) if they dont exist.

This can happen servers which have a lobby/static world, or ones that want to preserve the updated worlds (?)
