### ISSUE TITLE
RFC: autopull - Pull modified files?

### ISSUE THREAD

**Issue by TheAlan404** [ParadigmMC/mcman#28]
The idea is that filenames would be written in `server.toml` and mcman would `pull` the said files from server/ to config/ if they were modified

For example:

```toml
[extra]
autopull = [
  "whitelist.json"
]
```

would this be a good idea?
