### ISSUE TITLE
add more server software

### ISSUE THREAD

**Issue by 0PandaDEV** [ParadigmMC/mcman#30]
- pufferfish
- folia
- plazma
- sponge

**Comment by TheAlan404** [comment]
yea sure we can add more shortcut names... to some of them?

Pufferfish:
```toml
[jar]
type = "jenkins"
url = "https://ci.pufferfish.host/"
# one of these
job = "Pufferfish-${mcver}"
job = "Pufferfish-Purpur-${mcver}"
job = "PufferfishPlus-${mcver}"
# build latest, artifact first
```

Folia: requires building so kinda impossible without any CI building it rn (building from source feature is planned)

Plazma:
```toml
[jar]
type = "ghrel"
repo = "PlazmaMC/Plazma"
tag = "latest-${mcver}"
# unfortunately asset must be set manually
# because of extra build id/etc included in the
# filenames.
#asset = "plazma-paperclip-${}-reobf.jar"
```

Sponge:
```toml
[jar]
type = "maven"
url = "https://repo.spongepowered.org/repository/maven-releases/"
group = "org.spongepowered"
artifact = "spongeforge" # or "spongevanilla"
# version used as search
version = "${mcver}"
filename = "${artifact}-${version}-universal.jar"
```
