### ISSUE TITLE
server port not changed

### ISSUE THREAD

**Issue by EldosHD** [ParadigmMC/mcman#49]
I changed the `PORT` variable in `server.toml` to `25001`, but it didn't change in `server.properties` after running `mcman build`.
Is this a bug, or am I doing something wrong.

This is `server.toml` (without all the mods):

```toml
name = "exploration++"
mc_version = "1.20.1"

[jar]
type = "fabric"
loader = "0.15.3"
installer = "latest"

[variables]
PORT = "25001"

[launcher]
eula_args = true
nogui = true
```

And this is the generated `server.properties`:
```
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=world
motd=${SERVER_NAME\:A Minecraft Server}
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
use-native-transport=true
max-players=20
online-mode=true
enable-status=true
allow-flight=false
initial-disabled-packs=
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=10
rcon.password=
player-idle-timeout=0
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
function-permission-level=2
initial-enabled-packs=vanilla,fabric,tectonic\:terratonic
level-type=bclib\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
spawn-protection=16
resource-pack-sha1=
max-world-size=29999984
```
