### ISSUE TITLE
Test success hook do not run

### ISSUE THREAD

**Issue by AntwortEinesLebens** [ParadigmMC/mcman#58]
Hi,

I wrote a hook to move some addons inside the right folder when the test succeeds.
Even though it says that the test passed, my hook is not run.

The postbuild hook works perfectly fine.

I use mcman version 0.4.4

Here the hook inside the `server.toml`:

```toml
[hooks.move-bentobox-addons-in]
linux = "move-bentobox-addons-in.sh"
windows = "move-bentobox-addons-in.bat"
when = "testsuccess"
onfail = "Error"
output = "hide"
description = "Move all BentoBox's addons to the BentoBox's \"addons\" folder"
```

Is my hook correct?
